"""Explicit portable pure-FM training; no work is performed at import time."""
from .runtime import configure_stable_runtime
import argparse
from pathlib import Path
import time
import torch
from .artifacts import atomic_json, file_sha256, state_sha256
from .checkpoint import DEFAULT_CONFIG
from .data import load_archive, NativeTrainingStream, native_collate, model_inputs
from .training import train_step, make_optimizer, masked_fm_loss
from .model import native_execution

SCHEMA = "native_t1_training_v1"


def positive_int(value):
    result = int(value)
    if result <= 0:
        raise argparse.ArgumentTypeError("Expected a positive integer")
    return result


def build_parser():
    parser = argparse.ArgumentParser(description="Pure Native T1 training on the registered N112 two-parent task")
    parser.add_argument("--inputs", type=Path, required=True, help="NPZ generated by native_t1 prepare")
    parser.add_argument("--inputs-sha256", help="Optional expected prepared archive hash")
    init = parser.add_mutually_exclusive_group(required=True)
    init.add_argument("--official-checkpoint", type=Path, help="External official chair last.pt (EMA)")
    init.add_argument("--init-t1", type=Path, help="A checkpoint produced by this portable trainer; fresh AdamW")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--out", type=Path, required=True, help="New run directory, never overwritten")
    parser.add_argument("--seed", type=int, help="Fresh input stream seed; defaults to 10")
    parser.add_argument("--continue-stream", action="store_true",
                        help="Restore input RNG from --init-t1; optimizer is still reset")
    budget = parser.add_mutually_exclusive_group(required=True)
    budget.add_argument("--updates", type=positive_int, help="Exact number of additional optimizer updates")
    budget.add_argument("--check-only", action="store_true",
                        help="One real CUDA forward/backward and zero updates; no checkpoint or generation")
    parser.add_argument("--save-every", type=positive_int, default=250)
    return parser


def make_stream(args, archive):
    if args.continue_stream:
        if args.init_t1 is None or args.seed is not None:
            raise ValueError("--continue-stream requires --init-t1 and cannot be combined with --seed")
        payload = torch.load(args.init_t1, map_location="cpu", weights_only=True, mmap=True)
        if payload.get("schema") != SCHEMA or payload.get("input_sha256") != archive.sha256:
            raise ValueError("Input stream restore requires the same prepared archive and portable schema")
        state = payload["stream_state"]
        if state["arm"] != "Native_correct":
            raise ValueError("Only correct-context pure T1 training is supported")
        stream = NativeTrainingStream(archive, seed=state["seed"])
        stream.load_state_dict(state)
        del payload
        return stream, "restored_input_rng_fresh_optimizer"
    return NativeTrainingStream(archive, seed=10 if args.seed is None else args.seed), "fresh_input_rng_fresh_optimizer"


def save_checkpoint(path, model, optimizer, stream, archive, config_path, base_updates, completed):
    if path.exists():
        raise FileExistsError(path)
    from .portable_checkpoint import NATIVE_META, config_sha256
    payload = dict(schema=SCHEMA, native_meta=dict(NATIVE_META), model=model.state_dict(), optimizer=optimizer.state_dict(),
                   config_sha256=config_sha256(config_path), completed_updates=completed,
                   base_cumulative_updates=base_updates, cumulative_updates=base_updates+completed,
                   stream_state=stream.state_dict(), stream_seed=stream.seed, input_sha256=archive.sha256,
                   loss="masked_free_fm", num_faces=112, train_K=[4,8,12], optimizer_reset_at_start=True,
                   model_state_sha256=state_sha256(model), optimizer_step_in_progress=False, batch_in_progress=False)
    temporary = path.with_suffix(".pt.partial")
    if temporary.exists():
        raise FileExistsError(temporary)
    torch.save(payload, temporary)
    temporary.replace(path)
    return dict(path=str(path.resolve()), bytes=path.stat().st_size, sha256=file_sha256(path),
                model_state_sha256=payload["model_state_sha256"], cumulative_updates=base_updates+completed)


def check_backward(model, samples, counts):
    """Real deterministic GPU backward, with no optimizer constructed or update."""
    batch = native_collate([samples[0]], "cuda")
    denominator = 9*sum(int((s["valid_mask"] & ~s["known_mask"]).sum()) for s in samples)
    model.zero_grad(set_to_none=True)
    with native_execution(model, coordinates=batch["xt"]) as runtime:
        counts["forward_attempts"] = counts.get("forward_attempts", 0)+1
        velocity = model(*model_inputs(batch)).float()
        counts["forward_returns"] = counts.get("forward_returns", 0)+1
        loss = masked_fm_loss(velocity, batch["u"], batch["valid_mask"], batch["known_mask"],
                              denominator=denominator)
        if not bool(torch.isfinite(loss)):
            raise RuntimeError("Nonfinite preflight loss")
        counts["backward_attempts"] = counts.get("backward_attempts", 0)+1
        loss.backward()
        counts["backward_returns"] = counts.get("backward_returns", 0)+1
    norm = float(torch.nn.utils.clip_grad_norm_(model.parameters(), 1., error_if_nonfinite=True))
    model.zero_grad(set_to_none=True)
    torch.cuda.synchronize()
    return dict(loss=float(loss.detach()), grad_norm_before_clip=norm, runtime=runtime,
                tested_microbatches=1, optimizer_constructed=False, optimizer_updates=0)


def run(args):
    if args.out.exists():
        raise FileExistsError(args.out)
    if args.continue_stream and (args.init_t1 is None or args.seed is not None):
        raise ValueError("--continue-stream requires --init-t1 and no --seed")
    archive = load_archive(args.inputs, args.inputs_sha256)
    # Validate all required cases/pre-OT arrays before reading large weights.
    stream, stream_mode = make_stream(args, archive)
    args.out.mkdir(parents=True)
    report = dict(status="RUNNING", mode="check-only" if args.check_only else "train",
                  input_path=str(archive.path), input_sha256=archive.sha256,
                  requested_updates=0 if args.check_only else args.updates, completed_updates=0,
                  stream_mode=stream_mode, stream_start=stream.state_dict(),
                  counts=dict(forward_attempts=0, forward_returns=0, backward_attempts=0, backward_returns=0,
                              optimizer_step_attempts=0, optimizer_updates=0, OT_calls=0),
                  checkpoints=[], logs=[], update_in_progress=False)
    start = time.perf_counter()
    atomic_json(args.out/"run.json", report)
    try:
        from .portable_checkpoint import load_official_initialization, load_trained_checkpoint
        configure_stable_runtime()
        if args.official_checkpoint is not None:
            model, report["initialization"] = load_official_initialization(args.official_checkpoint, args.config)
            base_updates = 0
        else:
            model, report["initialization"] = load_trained_checkpoint(args.init_t1, args.config)
            base_updates = int(report["initialization"]["cumulative_updates"])
        report["base_cumulative_updates"] = base_updates
        model.set_trainable(True).eval()
        if args.check_only:
            samples = stream.next_effective_batch()
            report["counts"]["OT_calls"] += 8
            before = state_sha256(model)
            report["preflight"] = check_backward(model, samples, report["counts"])
            after = state_sha256(model)
            if after != before:
                raise RuntimeError("Check-only changed model parameters")
            report.update(parameter_state_before=before, parameter_state_after=after,
                          first_batch=stream.last_audit, status="PASS")
        else:
            optimizer = make_optimizer(model)
            with (args.out/"input_stream.jsonl").open("x", encoding="utf-8") as input_log:
                import json
                for step in range(1, args.updates+1):
                    report["update_in_progress"] = True
                    samples = stream.next_effective_batch()
                    report["counts"]["OT_calls"] += 8
                    input_log.write(json.dumps(stream.last_audit, allow_nan=False)+"\n")
                    input_log.flush()
                    metrics = train_step(model, optimizer, samples, counts=report["counts"])
                    report["completed_updates"] = step
                    report["update_in_progress"] = False
                    if step in (1,100,250,args.updates):
                        report["logs"].append(dict(step=step, **metrics))
                        print(f"step={step}/{args.updates} FM={metrics['loss']:.7f}", flush=True)
                    if step % args.save_every == 0 or step == args.updates:
                        path = args.out/f"additional_step{step}_cumulative_step{base_updates+step}.pt"
                        report["checkpoints"].append(save_checkpoint(path, model, optimizer, stream, archive,
                                                                    args.config, base_updates, step))
                    # Counts survive interruptions at step boundaries.
                    atomic_json(args.out/"run.json", report)
            report["status"] = "PASS"
        report["stream_end"] = stream.state_dict()
    except BaseException as error:
        report.update(status="STOPPED", error=repr(error))
        raise
    finally:
        report["seconds"] = time.perf_counter()-start
        atomic_json(args.out/"run.json", report)
    print("PASS: "+str(args.out.resolve()), flush=True)
    return report


def main(argv=None):
    return run(build_parser().parse_args(argv))


if __name__ == "__main__":
    main()
