"""Explicit portable pure-FM training for Native T1 and its optional T_geo branch."""
from .runtime import configure_stable_runtime
import argparse
from pathlib import Path
import time
import torch
from .artifacts import atomic_json, file_sha256, state_sha256
from .checkpoint import DEFAULT_CONFIG
from .data import load_archive, NativeTrainingStream, native_collate, model_inputs
from .training import train_step, make_optimizer, masked_fm_loss
from .model import native_execution
from .accounting import count_ot_calls

SCHEMA = "native_t1_training_v1"


def positive_int(value):
    result = int(value)
    if result <= 0:
        raise argparse.ArgumentTypeError("Expected a positive integer")
    return result


def build_parser():
    parser = argparse.ArgumentParser(description="Native T1 / T_geo pure-FM training on the registered N112 two-parent task")
    parser.add_argument("--inputs", type=Path, required=True, help="NPZ generated by native_t1 prepare")
    parser.add_argument("--inputs-sha256", help="Optional expected prepared archive hash")
    init = parser.add_mutually_exclusive_group(required=True)
    init.add_argument("--official-checkpoint", type=Path, help="External official chair last.pt (EMA)")
    init.add_argument("--init-t1", type=Path, help="A checkpoint produced by this portable trainer; fresh AdamW")
    init.add_argument("--init-geo", type=Path, help="A T_geo checkpoint; fresh AdamW")
    parser.add_argument("--context-encoder", choices=("none", "geo"), default="none",
                        help="Default: unchanged pure T1; geo adds the known-face geometry encoder")
    parser.add_argument("--encoder-seed", type=int,
                        help="Fresh geo encoder initialization seed (default 1010); not used with --init-geo")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--out", type=Path, required=True, help="New run directory, never overwritten")
    parser.add_argument("--seed", type=int, help="Fresh input stream seed; defaults to 10")
    parser.add_argument("--continue-stream", action="store_true",
                        help="Restore input RNG from --init-t1 or --init-geo; optimizer is still reset")
    budget = parser.add_mutually_exclusive_group(required=True)
    budget.add_argument("--updates", type=positive_int, help="Exact number of additional optimizer updates")
    budget.add_argument("--check-only", action="store_true",
                        help="One real CUDA forward/backward and zero updates; no checkpoint or generation")
    parser.add_argument("--save-every", type=positive_int, default=250)
    return parser


def make_stream(args, archive):
    if args.continue_stream:
        checkpoint = args.init_t1 or args.init_geo
        if checkpoint is None or args.seed is not None:
            raise ValueError("--continue-stream requires --init-t1 or --init-geo and no --seed")
        from .geometry_checkpoint import SCHEMA as GEO_SCHEMA, LEGACY_SCHEMA
        payload = torch.load(checkpoint, map_location="cpu", weights_only=True, mmap=True)
        schemas = (SCHEMA,) if args.init_t1 else (GEO_SCHEMA, LEGACY_SCHEMA)
        if payload.get("schema") not in schemas or payload.get("input_sha256") != archive.sha256:
            raise ValueError("Input stream restore requires the same prepared archive and portable schema")
        state = payload["stream_state"]
        if state["arm"] != "Native_correct":
            raise ValueError("Only correct-context Native training is supported")
        stream = NativeTrainingStream(archive, seed=state["seed"])
        stream.load_state_dict(state)
        del payload
        return stream, "restored_input_rng_fresh_optimizer"
    return NativeTrainingStream(archive, seed=10 if args.seed is None else args.seed), "fresh_input_rng_fresh_optimizer"


def save_checkpoint(path, model, optimizer, stream, archive, config_path, base_updates, completed):
    if path.exists():
        raise FileExistsError(path)
    from .portable_checkpoint import NATIVE_META, config_sha256
    payload = dict(schema=SCHEMA, native_meta=dict(NATIVE_META), model=model.state_dict(), optimizer=optimizer.state_dict(),
                   config_sha256=config_sha256(config_path), completed_updates=completed,
                   base_cumulative_updates=base_updates, cumulative_updates=base_updates+completed,
                   stream_state=stream.state_dict(), stream_seed=stream.seed, input_sha256=archive.sha256,
                   loss="masked_free_fm", num_faces=112, train_K=[4,8,12], optimizer_reset_at_start=True,
                   model_state_sha256=state_sha256(model), optimizer_step_in_progress=False, batch_in_progress=False)
    temporary = path.with_suffix(".pt.partial")
    if temporary.exists():
        raise FileExistsError(temporary)
    torch.save(payload, temporary)
    temporary.replace(path)
    return dict(path=str(path.resolve()), bytes=path.stat().st_size, sha256=file_sha256(path),
                model_state_sha256=payload["model_state_sha256"], cumulative_updates=base_updates+completed)


def check_backward(model, samples, counts):
    """Real deterministic GPU backward, with no optimizer constructed or update."""
    batch = native_collate([samples[0]], "cuda")
    denominator = 9*sum(int((s["valid_mask"] & ~s["known_mask"]).sum()) for s in samples)
    model.zero_grad(set_to_none=True)
    with native_execution(model, coordinates=batch["xt"]) as runtime:
        counts["forward_attempts"] = counts.get("forward_attempts", 0)+1
        velocity = model(*model_inputs(batch)).float()
        counts["forward_returns"] = counts.get("forward_returns", 0)+1
        loss = masked_fm_loss(velocity, batch["u"], batch["valid_mask"], batch["known_mask"],
                              denominator=denominator)
        if not bool(torch.isfinite(loss)):
            raise RuntimeError("Nonfinite preflight loss")
        counts["backward_attempts"] = counts.get("backward_attempts", 0)+1
        loss.backward()
        counts["backward_returns"] = counts.get("backward_returns", 0)+1
    norm = float(torch.nn.utils.clip_grad_norm_(model.parameters(), 1., error_if_nonfinite=True))
    model.zero_grad(set_to_none=True)
    torch.cuda.synchronize()
    return dict(loss=float(loss.detach()), grad_norm_before_clip=norm, runtime=runtime,
                tested_microbatches=1, optimizer_constructed=False, optimizer_updates=0)


def encoder_update_metrics(encoder, before):
    """Selected-step, post-clip gradients and actual branch parameter deltas."""
    groups = {}
    for name, parameter in encoder.named_parameters():
        group = groups.setdefault(name.split(".")[0], dict(parameter_squared=0., gradient_squared=0., update_squared=0.))
        group["parameter_squared"] += float(parameter.detach().square().sum())
        group["gradient_squared"] += 0. if parameter.grad is None else float(parameter.grad.detach().square().sum())
        group["update_squared"] += float((parameter.detach()-before[name]).square().sum())
    return {name: dict(parameter_l2=values["parameter_squared"]**.5,
                       gradient_l2_after_clip=values["gradient_squared"]**.5,
                       actual_update_l2=values["update_squared"]**.5)
            for name, values in groups.items()}


def run(args):
    if args.out.exists():
        raise FileExistsError(args.out)
    if args.seed is not None and not 0 <= args.seed <= 2**32-1-70000:
        raise ValueError("--seed must be between 0 and 2**32-1-70000 for the five input RNGs")
    if args.encoder_seed is not None and not 0 <= args.encoder_seed < 2**63:
        raise ValueError("--encoder-seed must be between 0 and 2**63-1")
    if args.init_geo is not None and args.context_encoder != "geo":
        raise ValueError("--init-geo requires --context-encoder geo")
    if args.encoder_seed is not None and (args.context_encoder != "geo" or args.init_geo is not None):
        raise ValueError("--encoder-seed is only for a newly attached geo encoder")
    if args.continue_stream and ((args.init_t1 is None and args.init_geo is None) or args.seed is not None):
        raise ValueError("--continue-stream requires --init-t1 or --init-geo and no --seed")
    archive = load_archive(args.inputs, args.inputs_sha256)
    # Validate all required cases/pre-OT arrays before reading large weights.
    stream, stream_mode = make_stream(args, archive)
    args.out.mkdir(parents=True)
    report = dict(status="RUNNING", mode="check-only" if args.check_only else "train",
                  context_encoder=args.context_encoder, input_path=str(archive.path), input_sha256=archive.sha256,
                  requested_updates=0 if args.check_only else args.updates, completed_updates=0,
                  stream_mode=stream_mode, stream_start=stream.state_dict(),
                  counts=dict(forward_attempts=0, forward_returns=0, backward_attempts=0, backward_returns=0,
                              optimizer_step_attempts=0, optimizer_updates=0, OT_calls=0),
                  checkpoints=[], logs=[], update_in_progress=False)
    start = time.perf_counter()
    atomic_json(args.out/"run.json", report)
    try:
        from .portable_checkpoint import load_official_initialization, load_trained_checkpoint
        configure_stable_runtime()
        if args.official_checkpoint is not None:
            model, report["initialization"] = load_official_initialization(args.official_checkpoint, args.config)
            base_updates = 0
        elif args.init_geo is not None:
            from .geometry_checkpoint import load_geometry_checkpoint
            model, report["initialization"] = load_geometry_checkpoint(args.init_geo, args.config)
            base_updates = int(report["initialization"]["cumulative_updates"])
        else:
            model, report["initialization"] = load_trained_checkpoint(args.init_t1, args.config)
            base_updates = int(report["initialization"]["cumulative_updates"])
        if args.context_encoder == "geo" and args.init_geo is None:
            from .context_geometry import attach_context_encoder
            report["encoder_initialization"] = attach_context_encoder(
                model, "geo", seed=1010 if args.encoder_seed is None else args.encoder_seed)
        report["base_cumulative_updates"] = base_updates
        model.set_trainable(True).eval()
        if args.check_only:
            with count_ot_calls(report["counts"]):
                samples = stream.next_effective_batch()
            before = state_sha256(model)
            report["preflight"] = check_backward(model, samples, report["counts"])
            after = state_sha256(model)
            if after != before:
                raise RuntimeError("Check-only changed model parameters")
            report.update(parameter_state_before=before, parameter_state_after=after,
                          first_batch=stream.last_audit, status="PASS")
        else:
            optimizer = make_optimizer(model)
            with (args.out/"input_stream.jsonl").open("x", encoding="utf-8") as input_log:
                import json
                for step in range(1, args.updates+1):
                    report["update_in_progress"] = True
                    with count_ot_calls(report["counts"]):
                        samples = stream.next_effective_batch()
                    input_log.write(json.dumps(stream.last_audit, allow_nan=False)+"\n")
                    input_log.flush()
                    log_step = step in (1,100,250,args.updates)
                    encoder = getattr(model, "context_encoder", None)
                    before_encoder = ({name: value.detach().clone() for name, value in encoder.named_parameters()}
                                      if log_step and encoder is not None else None)
                    metrics = train_step(model, optimizer, samples, counts=report["counts"])
                    if before_encoder is not None:
                        metrics["encoder"] = encoder_update_metrics(encoder, before_encoder)
                    report["completed_updates"] = step
                    report["update_in_progress"] = False
                    if log_step:
                        report["logs"].append(dict(step=step, **metrics))
                        print(f"step={step}/{args.updates} FM={metrics['loss']:.7f}", flush=True)
                    if step % args.save_every == 0 or step == args.updates:
                        path = args.out/f"additional_step{step}_cumulative_step{base_updates+step}.pt"
                        if args.context_encoder == "geo":
                            from .geometry_checkpoint import save_geometry_checkpoint
                            saved = save_geometry_checkpoint(path, model, optimizer, stream, archive,
                                config_path=args.config, base_identity=report["initialization"],
                                base_updates=base_updates, completed=step)
                        else:
                            saved = save_checkpoint(path, model, optimizer, stream, archive,
                                                    args.config, base_updates, step)
                        report["checkpoints"].append(saved)
                    # Counts survive interruptions at step boundaries.
                    atomic_json(args.out/"run.json", report)
            report["status"] = "PASS"
        report["stream_end"] = stream.state_dict()
    except BaseException as error:
        report.update(status="STOPPED", error=repr(error))
        raise
    finally:
        report["seconds"] = time.perf_counter()-start
        atomic_json(args.out/"run.json", report)
    print("PASS: "+str(args.out.resolve()), flush=True)
    return report


def main(argv=None):
    return run(build_parser().parse_args(argv))


if __name__ == "__main__":
    main()
